export const strings = {
  appName: 'Supabase Notes',
  welcome: 'Welcome to Supabase Notes',
  loginDescription: 'Log in to continue Supabase Notes',
  registerDescription: 'Create an account to continue using Supabase Notes.',
  emailAddress: 'Email Address',
  password: 'Password',
  forgotPassword: 'Forgot Password?',
  forgotPasswordDesc:
    'Enter the email address associated with your account. We will email a code to reset your Password.',
  submit: 'SUBMIT',
  emailLowercaseOnly: 'Email should be in lowercase letters only',
  pleaseEnterValidEmail: 'Please enter a valid email',
  pleaseEnterEmail: 'Please enter an email',
  loginCapital: 'LOG IN',
  pleaseEnterPassword: 'Please enter a password',
  confirmPasswordMinLength: 'Password must be at least 6 characters long',
  changePasswordText:
    'Your password must be more than six characters long and include a combination of letters, numbers, and special characters (e.g., !$@%#).',
  passwordCannotContainSpaces: 'Password cannot contain spaces.',
  orContinueWith: 'or continue with',
  noAccount: "Don't have an account? ",
  signUp: 'Sign Up',
  createAccount: 'Create Account',
  firstName: 'First Name',
  lastName: 'Last Name',
  userName: 'User Name',
  confirmPassword: 'Confirm Password',
  iAgree: 'I agree to the ',
  privacy_policy: 'Privacy Policy',
  subscription: 'Subscription',
  privacy_policy_type: 'privacy_policy',
  and: 'and ',
  terms_conditions: 'Terms & Conditions',
  terms_and_condition_type: 'terms_and_condition',
  signUpCapital: 'SIGN UP',
  conditionsError:
    'You must accept the Terms & Conditions and Privacy Policy to proceed.',
  enterConfirmPassword: 'Please enter the confirm password',
  pleaseEnterMessage: 'Please enter an message',
  pleaseEnterSubject: 'Please enter an subject',
  pleaseEnterFullName: 'Please enter a first name',
  pleaseEnterLastName: 'Please enter a last name',
  minLengthErrFullNameError: 'First name must be at least 3 characters long',
  minLengthErrLastNameError: 'Last name must be at least 3 characters long',
  validFullNameError: 'Please enter a valid first name',
  validLastNameError: 'Please enter a valid last name',
  fullName_error: 'First name cannot start with a space',
  lastName_error: 'Last name cannot start with a space',
  nameCannotHaveMultipleSpaces: 'First name cannot have multiple spaces',
  lastNameCannotHaveMultipleSpaces: 'Last name cannot have multiple spaces',
  nameCannotEndWithSpace: 'First name cannot end with a space',
  lastNameCannotEndWithSpace: 'Last name cannot end with a space',
  enter_nickName: 'Please enter a user name',
  nickName_length: 'User name must be at least 3 characters long',
  enter_nick_name: 'Please enter a valid user name',
  lastName_cannot_start_space: 'USer name cannot start with a space',
  nickName_multiple_space: 'User name cannot have multiple spaces',
  nikeName_cannot_last_space: 'USername cannot end with a space',
  nickName_cannot_end_space: 'User name cannot end with a space',
  changeConfirmPasswordText:
    'Your password must be more than six characters long and include a combination of letters, numbers, and special characters (e.g., !$@%#).',
  confirmPasswordCannotContainSpaces: 'Password cannot contain spaces.',
  passwordsDoNotMatch: 'Passwords do not match',
  alreadyHaveAccount: 'Already have an account? ',
  login: 'Log in',
  verificationCodeLengthError: 'Verification code must be exactly 6 digits',
  verificationCodeError: 'Please enter a verification code',
  verificationCodeInvalid: 'Verification code must be a valid number',
  verifyEmail: 'Verify Your Email Address',
  codeVerification: 'Code Verification',
  codeVerificationDesc:
    'We’ve sent a 6-digit code to your email. Please enter it below to continue.',
  verificationCodePlaceholder: '6 - digit code here',
  verify: 'VERIFY',
  didNotReceiveCode: 'Didn’t receive code?',
  sendAgain: 'Send again',
  resetYourPassword: 'Reset Your Password',
  resetYourPasswordDesc:
    'Enter a new password to secure your account. Make sure it’s strong and easy to remember.',
  resetPassword: 'RESET PASSWORD',
  profile: 'Profile',
  logOut: 'Log Out',
  delete_account: 'Delete Account',
  deleteAccountConfirmation: 'Are you sure you want to delete your account?',
  delete: 'Delete',
  currentlyOffline: 'You are currently offline',
  changeProfileImage: 'Change Profile Image',
  enter_nickname: 'Nick Name',
  save: 'SAVE',
  logoutConfirmation: 'Are you sure you want to log out from\nSupabase Notes?',
  cancel: 'Cancel',
  logoutDesc: 'You can log back in anytime with your credentials.',
  myNotes: 'My Notes',
  notesTitle: 'My Notes',
  createNote: 'Create Note',
  editNote: 'Edit Note',
  viewNote: 'View Note',
  updateNote: 'Update Note',
  deleteNote: 'Delete Note',
  noteTitle: 'Note Title',
  noteContent: 'Note Content',
  noteTitlePlaceholder: 'Note Title',
  noteContentPlaceholder: 'Note Content',
  titleRequired: 'Title is required',
  contentRequired: 'Content is required',
  noteCreatedSuccess: 'Note created successfully',
  noteUpdatedSuccess: 'Note updated successfully',
  noteDeletedSuccess: 'Note deleted successfully',
  failedToLoadNotes: 'Failed to load notes',
  failedToCreateNote: 'Failed to create note',
  failedToUpdateNote: 'Failed to update note',
  failedToDeleteNote: 'Failed to delete note',
  deleteNoteConfirmation: 'Are you sure you want to delete this note?',
  deleteNoteDesc: 'This action cannot be undone.',
  noNotesYet: 'No notes yet',
  createFirstNote: 'Create your first note to get started',
  untitledNote: 'Untitled Note',
  noContent: 'No content',
  // Common error messages
  userNotAuthenticated: 'User not authenticated',
  somethingWentWrong: 'Something went wrong',
  somethingWentWrongLogout: 'Something went wrong during logout',
  failedToLogout: 'Failed to logout',
  loggedOutSuccess: 'Logged out successfully',
  failedToDeleteAccount: 'Failed to delete account',
  accountDeletedSuccess: 'Account deleted successfully',
  accountDataDeleted: 'Account data deleted. Please contact support to complete account deletion.',
  // Network messages
  noInternetCreateNote:
    'No internet connection. Please connect to create notes.',
  noInternetUpdateNote:
    'No internet connection. Please connect to update notes.',
  noInternetDeleteNote:
    'No internet connection. Please connect to delete notes.',
  // Display name related
  displayName: 'Display Name',
  pleaseEnterDisplayName: 'Please enter your display name',
  displayNameMinLength: 'Display name must be at least 2 characters',
  pleaseEnterValidDisplayName: 'Please enter a valid display name',
};
