default_platform(:ios)

platform :ios do
  desc "Build and upload a beta to TestFlight"
  lane :beta do |options|
    release_notes = options[:release_notes] || ENV["RELEASE_NOTES"] || "Beta build from CI"

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      duration: 1200,
      in_house: false
    )

    build_app(
      workspace: "ProjectTemplate.xcworkspace",
      scheme: "SupabaseNotes",
      export_method: "app-store",
      output_directory: "build",
      output_name: "SupabaseNotes.ipa"
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: ENV["APP_IDENTIFIER"],
      changelog: release_notes,
      distribute_external: true,
      groups: ["Internal Testers"]
    )
  end
end


